server:
  port: 8888
spring:
  application:
    name: remoteconfigserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Majinglong/aisringcloud.git
          search-paths: config
          username: root # 改成自己的用户名
          password: root # 改成自己的用户名
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/