server:
  port: 8090
spring:
  application:
    name: zipkinclient
  sleuth:  #zipkin展示，sleth做监控
    web:
      client:
        enabled: true #启用请求监控
    sampler:
      probability: 1.0 # 设置采样比例，默认是1.0
  zipkin:
    base-url: http://localhost:9090/  #zipkin server地址

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/